/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as ParkingIdRouteImport } from './routes/parking.$id'
import { Route as BookingsNewRouteImport } from './routes/bookings.new'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppVendorParkingRouteImport } from './routes/_app/vendor/parking'
import { Route as AppAdminVendorsRouteImport } from './routes/_app/admin/vendors'
import { Route as AppAdminDriversRouteImport } from './routes/_app/admin/drivers'
import { Route as AppAdminBookingsRouteImport } from './routes/_app/admin/bookings'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingIdRoute = ParkingIdRouteImport.update({
  id: '/parking/$id',
  path: '/parking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorParkingRoute = AppVendorParkingRouteImport.update({
  id: '/vendor/parking',
  path: '/vendor/parking',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminVendorsRoute = AppAdminVendorsRouteImport.update({
  id: '/admin/vendors',
  path: '/admin/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDriversRoute = AppAdminDriversRouteImport.update({
  id: '/admin/drivers',
  path: '/admin/drivers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBookingsRoute = AppAdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/bookings/new': typeof BookingsNewRoute
  '/parking/$id': typeof ParkingIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/admin/bookings': typeof AppAdminBookingsRoute
  '/admin/drivers': typeof AppAdminDriversRoute
  '/admin/vendors': typeof AppAdminVendorsRoute
  '/vendor/parking': typeof AppVendorParkingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/bookings/new': typeof BookingsNewRoute
  '/parking/$id': typeof ParkingIdRoute
  '/bookings': typeof BookingsIndexRoute
  '/admin/bookings': typeof AppAdminBookingsRoute
  '/admin/drivers': typeof AppAdminDriversRoute
  '/admin/vendors': typeof AppAdminVendorsRoute
  '/vendor/parking': typeof AppVendorParkingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/bookings/new': typeof BookingsNewRoute
  '/parking/$id': typeof ParkingIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/_app/admin/bookings': typeof AppAdminBookingsRoute
  '/_app/admin/drivers': typeof AppAdminDriversRoute
  '/_app/admin/vendors': typeof AppAdminVendorsRoute
  '/_app/vendor/parking': typeof AppVendorParkingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/bookings/new'
    | '/parking/$id'
    | '/bookings/'
    | '/admin/bookings'
    | '/admin/drivers'
    | '/admin/vendors'
    | '/vendor/parking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/bookings/new'
    | '/parking/$id'
    | '/bookings'
    | '/admin/bookings'
    | '/admin/drivers'
    | '/admin/vendors'
    | '/vendor/parking'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/dashboard'
    | '/bookings/new'
    | '/parking/$id'
    | '/bookings/'
    | '/_app/admin/bookings'
    | '/_app/admin/drivers'
    | '/_app/admin/vendors'
    | '/_app/vendor/parking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  BookingsNewRoute: typeof BookingsNewRoute
  ParkingIdRoute: typeof ParkingIdRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking/$id': {
      id: '/parking/$id'
      path: '/parking/$id'
      fullPath: '/parking/$id'
      preLoaderRoute: typeof ParkingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/parking': {
      id: '/_app/vendor/parking'
      path: '/vendor/parking'
      fullPath: '/vendor/parking'
      preLoaderRoute: typeof AppVendorParkingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/vendors': {
      id: '/_app/admin/vendors'
      path: '/admin/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AppAdminVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/drivers': {
      id: '/_app/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AppAdminDriversRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/bookings': {
      id: '/_app/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AppAdminBookingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppAdminBookingsRoute: typeof AppAdminBookingsRoute
  AppAdminDriversRoute: typeof AppAdminDriversRoute
  AppAdminVendorsRoute: typeof AppAdminVendorsRoute
  AppVendorParkingRoute: typeof AppVendorParkingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAdminBookingsRoute: AppAdminBookingsRoute,
  AppAdminDriversRoute: AppAdminDriversRoute,
  AppAdminVendorsRoute: AppAdminVendorsRoute,
  AppVendorParkingRoute: AppVendorParkingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  BookingsNewRoute: BookingsNewRoute,
  ParkingIdRoute: ParkingIdRoute,
  BookingsIndexRoute: BookingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
