/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as ParkingsMapRouteImport } from './routes/parkings.map'
import { Route as ParkingsIdRouteImport } from './routes/parkings.$id'
import { Route as BookingsNewRouteImport } from './routes/bookings.new'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppVendorParkingsRouteImport } from './routes/_app/vendor/parkings'
import { Route as AppVendorDashboardRouteImport } from './routes/_app/vendor/dashboard'
import { Route as AppVendorBookingsRouteImport } from './routes/_app/vendor/bookings'
import { Route as AppAdminVendorsRouteImport } from './routes/_app/admin/vendors'
import { Route as AppAdminDriversRouteImport } from './routes/_app/admin/drivers'
import { Route as AppAdminBookingsRouteImport } from './routes/_app/admin/bookings'
import { Route as AppVendorParkingParkingIdRouteImport } from './routes/_app/vendor/parking_.$parkingId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingsMapRoute = ParkingsMapRouteImport.update({
  id: '/parkings/map',
  path: '/parkings/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingsIdRoute = ParkingsIdRouteImport.update({
  id: '/parkings/$id',
  path: '/parkings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorParkingsRoute = AppVendorParkingsRouteImport.update({
  id: '/vendor/parkings',
  path: '/vendor/parkings',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorDashboardRoute = AppVendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorBookingsRoute = AppVendorBookingsRouteImport.update({
  id: '/vendor/bookings',
  path: '/vendor/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminVendorsRoute = AppAdminVendorsRouteImport.update({
  id: '/admin/vendors',
  path: '/admin/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDriversRoute = AppAdminDriversRouteImport.update({
  id: '/admin/drivers',
  path: '/admin/drivers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBookingsRoute = AppAdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorParkingParkingIdRoute =
  AppVendorParkingParkingIdRouteImport.update({
    id: '/vendor/parking_/$parkingId',
    path: '/vendor/parking/$parkingId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/bookings/new': typeof BookingsNewRoute
  '/parkings/$id': typeof ParkingsIdRoute
  '/parkings/map': typeof ParkingsMapRoute
  '/bookings/': typeof BookingsIndexRoute
  '/admin/bookings': typeof AppAdminBookingsRoute
  '/admin/drivers': typeof AppAdminDriversRoute
  '/admin/vendors': typeof AppAdminVendorsRoute
  '/vendor/bookings': typeof AppVendorBookingsRoute
  '/vendor/dashboard': typeof AppVendorDashboardRoute
  '/vendor/parkings': typeof AppVendorParkingsRoute
  '/vendor/parking/$parkingId': typeof AppVendorParkingParkingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/bookings/new': typeof BookingsNewRoute
  '/parkings/$id': typeof ParkingsIdRoute
  '/parkings/map': typeof ParkingsMapRoute
  '/bookings': typeof BookingsIndexRoute
  '/admin/bookings': typeof AppAdminBookingsRoute
  '/admin/drivers': typeof AppAdminDriversRoute
  '/admin/vendors': typeof AppAdminVendorsRoute
  '/vendor/bookings': typeof AppVendorBookingsRoute
  '/vendor/dashboard': typeof AppVendorDashboardRoute
  '/vendor/parkings': typeof AppVendorParkingsRoute
  '/vendor/parking/$parkingId': typeof AppVendorParkingParkingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/bookings/new': typeof BookingsNewRoute
  '/parkings/$id': typeof ParkingsIdRoute
  '/parkings/map': typeof ParkingsMapRoute
  '/bookings/': typeof BookingsIndexRoute
  '/_app/admin/bookings': typeof AppAdminBookingsRoute
  '/_app/admin/drivers': typeof AppAdminDriversRoute
  '/_app/admin/vendors': typeof AppAdminVendorsRoute
  '/_app/vendor/bookings': typeof AppVendorBookingsRoute
  '/_app/vendor/dashboard': typeof AppVendorDashboardRoute
  '/_app/vendor/parkings': typeof AppVendorParkingsRoute
  '/_app/vendor/parking_/$parkingId': typeof AppVendorParkingParkingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/bookings/new'
    | '/parkings/$id'
    | '/parkings/map'
    | '/bookings/'
    | '/admin/bookings'
    | '/admin/drivers'
    | '/admin/vendors'
    | '/vendor/bookings'
    | '/vendor/dashboard'
    | '/vendor/parkings'
    | '/vendor/parking/$parkingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/bookings/new'
    | '/parkings/$id'
    | '/parkings/map'
    | '/bookings'
    | '/admin/bookings'
    | '/admin/drivers'
    | '/admin/vendors'
    | '/vendor/bookings'
    | '/vendor/dashboard'
    | '/vendor/parkings'
    | '/vendor/parking/$parkingId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/dashboard'
    | '/bookings/new'
    | '/parkings/$id'
    | '/parkings/map'
    | '/bookings/'
    | '/_app/admin/bookings'
    | '/_app/admin/drivers'
    | '/_app/admin/vendors'
    | '/_app/vendor/bookings'
    | '/_app/vendor/dashboard'
    | '/_app/vendor/parkings'
    | '/_app/vendor/parking_/$parkingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  BookingsNewRoute: typeof BookingsNewRoute
  ParkingsIdRoute: typeof ParkingsIdRoute
  ParkingsMapRoute: typeof ParkingsMapRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkings/map': {
      id: '/parkings/map'
      path: '/parkings/map'
      fullPath: '/parkings/map'
      preLoaderRoute: typeof ParkingsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkings/$id': {
      id: '/parkings/$id'
      path: '/parkings/$id'
      fullPath: '/parkings/$id'
      preLoaderRoute: typeof ParkingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/parkings': {
      id: '/_app/vendor/parkings'
      path: '/vendor/parkings'
      fullPath: '/vendor/parkings'
      preLoaderRoute: typeof AppVendorParkingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/dashboard': {
      id: '/_app/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof AppVendorDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/bookings': {
      id: '/_app/vendor/bookings'
      path: '/vendor/bookings'
      fullPath: '/vendor/bookings'
      preLoaderRoute: typeof AppVendorBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/vendors': {
      id: '/_app/admin/vendors'
      path: '/admin/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AppAdminVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/drivers': {
      id: '/_app/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AppAdminDriversRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/bookings': {
      id: '/_app/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AppAdminBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/parking_/$parkingId': {
      id: '/_app/vendor/parking_/$parkingId'
      path: '/vendor/parking/$parkingId'
      fullPath: '/vendor/parking/$parkingId'
      preLoaderRoute: typeof AppVendorParkingParkingIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppAdminBookingsRoute: typeof AppAdminBookingsRoute
  AppAdminDriversRoute: typeof AppAdminDriversRoute
  AppAdminVendorsRoute: typeof AppAdminVendorsRoute
  AppVendorBookingsRoute: typeof AppVendorBookingsRoute
  AppVendorDashboardRoute: typeof AppVendorDashboardRoute
  AppVendorParkingsRoute: typeof AppVendorParkingsRoute
  AppVendorParkingParkingIdRoute: typeof AppVendorParkingParkingIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAdminBookingsRoute: AppAdminBookingsRoute,
  AppAdminDriversRoute: AppAdminDriversRoute,
  AppAdminVendorsRoute: AppAdminVendorsRoute,
  AppVendorBookingsRoute: AppVendorBookingsRoute,
  AppVendorDashboardRoute: AppVendorDashboardRoute,
  AppVendorParkingsRoute: AppVendorParkingsRoute,
  AppVendorParkingParkingIdRoute: AppVendorParkingParkingIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  BookingsNewRoute: BookingsNewRoute,
  ParkingsIdRoute: ParkingsIdRoute,
  ParkingsMapRoute: ParkingsMapRoute,
  BookingsIndexRoute: BookingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
